version: '3.2'

services:

  mongodb:
    image: mongo:latest
    restart: unless-stopped

  graphql:
    build: ./apollo/.
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    environment:
      - "MONGO_URL=mongodb://mongo:27017/bsscursos"

  api:
    build: ./api/.
    restart: unless-stopped
    depends_on:
      - graphql
    ports:
      - "3000:3000"
    environment:
      - "APOLLO_BASE_URL=http://graphql:4000"

  web:
    build: ./web/.
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3001:3000"
    environment:
      - "API_BASE_URL=http://api/"
