POST http://localhost:4000/api/v1/pagamentos
Content-Type: application/json

{
    "valorPago": 100,
    "usuarioId": "661a9eebeaa675cead72be09",
    "pagbankId": "10", 
    "item": "661a9eebeaa675cead72be0e",
    "meioPagamento": "credito"
}

###
PUT http://localhost:4000/api/v1/pagamentos/by-id/661aafc909658cf9c6bee82a/dataRecebimento/14-04-2024

###
POST http://localhost:4000/api/v1/cursos
Content-Type: application/json

{
    "titulo": "Curso Teste",
    "descricao": "Esse é um curso de Teste",
    "qntHoras": 100,
    "professor": "Professor Raimundo",
    "paginaCurso": "curso.com",
    "paginaPropaganda": "curso.com/teste",
    "linkDePagamento": "linkpagamento.com",
    "ativo": false
}

### 
PUT http://localhost:4000/api/v1/cursos/by-id/661a9eebeaa675cead72be0e/ativacao-curso

###
PUT http://localhost:4000/api/v1/cursos/by-id/661a9eebeaa675cead72be0e/desativacao-curso


###

POST http://localhost:4000/api/v1/usuarios/login 
Content-Type: application/json

{
    "email": "marcos@bsscursos.tech",
    "senha": "Marcos123456"
}

###

GET http://localhost:4000/api/v1/cursos/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjJhOTdjZDVlMWUwYzcyOGZiZGFlMDkiLCJub20iOiJNYXJjb3MgR2FicmllbCIsImVtYSI6Im1hcmNvc0Bic3NjdXJzb3MudGVjaCIsImNlbCI6IjIxOTk3MTItMDAwMCIsInBhcCI6InN1cGVyYWRtaW4iLCJyZWYiOiIiLCJwd2QiOiJNYXJjb3MxMjM0NTYiLCJleHAiOjE3MTQwNzA4MTYzMzd9.YzQ0Rz6lk-jSozbLIHTRvd_Q8odaH4KqWhW2iV_p9_Q

###

POST http://localhost:4000/api/v1/usuarios
Content-Type: application/json

{
    "nome": "João",
    "email": "joao@yahoo.com",
    "senha": "Joao123456",
    "celular": "21994141414",
    "papel": "admin",
    "referencia": ""
}

###

GET http://localhost:4000/api/v1/youtube/videos/PLEi4rTuSjC8ocQ3nMAqndvaXNPMTVzyUP
Content-Type: application/json
X-Email: fulano@yahoo.com
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjJhZTNmY2M5MDM2MTc2NDVmNWM2YzAiLCJlbWEiOiJmdWxhbm9AeWFob28uY29tIiwiZXhwIjoxNzE0MDkyMDczMDg1fQ.GVLMN9Gh7bNK2qjCFyzZZItW3o--0U4_4JuHxd8EnR4

###

GET https://www.googleapis.com/youtube/v3/playlists?key=AIzaSyAhBFyvzkzC16D6T1sErj-rPRT6m-glhcs&part=snippet,contentDetails&channelId=UCoiqmXO10o7DI-CuBKdFueA&&maxResults=50